"""empty message

Revision ID: 8c44b20fa86f
Revises: 648cdf90185d
Create Date: 2017-08-31 19:23:58.966800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c44b20fa86f'
down_revision = '648cdf90185d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('_password', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'email')
    op.drop_column('admins', '_password')
    # ### end Alembic commands ###
